language: generic 
sudo: required
services: 
  - docker

before_install:
  - docker build -t monsieurgermain/dockertest -f Dockerfile.dev .

script:
  - docker run -e CI=true monsieurgermain/DockerTest npm run test