sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t monsieurgermain/dockertest -f Dockerfile.dev .

script:
  - docker run -e CI=true monsieurgermain/dockertest npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'dockertest'
  env: 'Dockertest-env'
  bucket_name: 'elasticbeanstalk-us-east-1-838185491950'
  bucket_path: 'dockertest'
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_ACCESS_KEY_SECRET"
